# Generated by Django 4.1.4 on 2023-10-17 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import proper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authApp', '0007_customerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('tx_ref', models.CharField(max_length=50, null=True, unique=True)),
                ('payment_type', models.CharField(max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.customerdetails')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proper.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(choices=[('Real Asset', 'Real Asset'), ('Real Banking', 'Real Banking'), ('Real Project', 'Real Project')], max_length=200, null=True)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('roi', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('price_per_slot', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('amount', models.CharField(max_length=255, null=True)),
                ('image1', models.ImageField(blank=True, null=True, storage=proper.models.MyCloudinaryStorage(), upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, storage=proper.models.MyCloudinaryStorage(), upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, storage=proper.models.MyCloudinaryStorage(), upload_to='images/')),
                ('slots_available', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('terms_and_condition', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Property',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.PositiveBigIntegerField(null=True)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proper.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
                ('bank', models.CharField(choices=[('access', 'Access Bank'), ('citibank', 'Citibank'), ('diamond', 'Diamond Bank'), ('ecobank', 'Ecobank'), ('fidelity', 'Fidelity Bank'), ('first_bank', 'First Bank'), ('fcmb', 'First City Monument Bank'), ('gtb', 'Guaranty Trust Bank'), ('heritage', 'Heritage Bank'), ('keystone', 'Keystone Bank'), ('polaris', 'Polaris Bank'), ('providus', 'Providus Bank'), ('stanbic', 'Stanbic IBTC Bank'), ('standard_chartered', 'Standard Chartered Bank'), ('sterling', 'Sterling Bank'), ('suntrust', 'Suntrust Bank'), ('union', 'Union Bank'), ('uba', 'United Bank for Africa'), ('unity', 'Unity Bank'), ('wema', 'Wema Bank'), ('zenith', 'Zenith Bank'), ('alat', 'ALAT by WEMA'), ('jubilee', 'Jubilee Bank'), ('sparkle', 'Sparkle'), ('kuda', 'Kuda Bank'), ('opay', 'OPay'), ('palmpay', 'PalmPay')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
